
// This file was automatically generated by @bearstudio/astro-typed-routes
// You should NOT make any changes in this file as it will be overwritten.

import { assignPaths } from '@bearstudio/astro-typed-routes';

const ROUTES_CONFIG = {
  "about": {},
  "new": {},
  "posts": {
    ":page": {}
  }
} as const;

export const ROUTES = assignPaths(ROUTES_CONFIG);
